a=input('Digite qualquer coisa:')
print(f'Você digitou {a}')
print('Você escreveu o tipo: ',type(a))
print('Ele é alfanúmerico?: ',a.isalnum())
print('Ele é númerico?: ',a.isnumeric())
print('Ele é alfabético?: ',a.isalpha())
print('Ele está em letras maiusculas? ', a.isupper())
print('Ele está em letras minusculas? ', a.islower())
print('Ele é imprimivel? ', a.isprintable())
print('Ele é um espaço? ', a.isspace())
print('Ele é um digito? ', a.isdigit())
